### ISSUE TITLE
Database: Update Tech Stack 

### ISSUE THREAD

**Issue by sm3dev** [nss-day-cohort-51/nss-day-cohort-51.github.io#111]
Update Tech Stack objects the database to show final lists.

Reference: Google Sheets file named **Tech Stack** in the Google Drive Shared folder.

Check that each Tech Stack object has an accurate **devType** property.

**Comment by fabform** [comment]
Handy to locate google sheet id
[find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)
