### ISSUE TITLE
Do Quality Assurance to check all links on dev cards and modal

### ISSUE THREAD

**Issue by SusieCodes** [nss-day-cohort-51/nss-day-cohort-51.github.io#124]
- Check social media 
- Check that youtube links show videos

**Comment by sm3dev** [comment]
Note: Colin's capstone image from Github is showing as a broken link. But the link takes you to the image in a browser
<img width="1522" alt="Screen Shot 2022-01-11 at 9 41 06 AM" src="https://user-images.githubusercontent.com/48193402/148974100-98b2a9b7-f550-4bc8-9cab-52ef0f247450.png">
.

`https://github.com/colinrmiller/screen-draft/blob/main/public/img/Logo.png`
