### ISSUE TITLE
Styling- Dev Card/List section

### ISSUE THREAD

**Issue by jmlashen** [nss-day-cohort-51/nss-day-cohort-51.github.io#46]
- [x] Section is mobile responsive
- [x] Sections are max 360px

**Comment by SusieCodes** [comment]
- [ ] Section is mobile responsive
- [ ] Sections are max 360px

**Comment by sm3dev** [comment]
I started updating the DevCard styling using Jake’s updated devcard Figma wireframe (3 Dec 2021). Still working as of 4 Dec 2021.

**Comment by sm3dev** [comment]
Notes from Commit:
mw-fix-swap-TechStackButton-BG-color: DevCard--Added hover conditional styling with 250ms transition to slightly slow down the hover effect; editted the title attribute in social icon links with action verbs and capitalization; Added name to Email icon so the title reads Email Michael Wright, for example.

**Comment by sm3dev** [comment]
Notes from Commit:
mw-fix-swap-TechStackButton-BG-colors: Cleaned up scss for social media buttons; set height for Fun Fact box to take 3 lines that takes a little more than 75 characters; removed a bunch of CSS lines from buttons.scss and added classes to DevCard JSX code and CSS to devlist.scss to make the devcard inner boxes styling even around the padding area; now the Fun Fact box and the dev-card__actions section buttons are even; added a box-shadow to the dev-card__action buttons that becomes 50% opaque when hovered over.

**Comment by sm3dev** [comment]
Notes from Commits:
mw-fix-swap-TechStackButton-BG-colors CTA--Added the 3 alien faces image; checked that the CTA section items stack; increased the font-size on the call to action button; added a title attribute to CTA button that says -Event Link Updates after 11 January 2022- so when the button is hovered over, the message shows."

mw-fix-swap-TechStackButton-BG-colors I'm closing out Issues 46 and 75; These are completed; I'm running npm run deploy after this commit to update the live cohort site with the working Above the Fold section.
